apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: troll
  namespace: n415-retreat
spec:
  image: {{ image }}
  leaderElection: true
  env: 
  - name: BUCKET_NAME
    value: n415-troll-guests
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi 
  gcp:
    buckets:
      - name: n415-troll-guests
        retentionPeriodDays: 2
